### ISSUE TITLE
starting various tweens lets them look jumpy

### ISSUE THREAD

**Issue by ccoenen** [pixelkind/tweety#1]
This starts a new tween for every click.

https://user-images.githubusercontent.com/124909/123171681-6a563580-d47c-11eb-94c7-71eb49760e8c.mp4

in the video, there's a clear "jump" on every click that I didn't expect.

i would instead expect the next transition to use the current x and y as start points.

**Comment by ccoenen** [comment]
here's a piece of example code that's similar to the code above, and produces similarly jumpy output for me:

```javascript
import Tween from './tweety.js';

const something = {
	radius: 100
};

function draw() {
	clear();
	circle(100, 100, something.radius);
}

function mouseClicked() {
	new Tween(something, 13, {
		radius: Math.random()*200
	});
}
```

**Comment by ccoenen** [comment]
interestingly, subsequent clicks don't animate at all anymore.

**Comment by pixelkind** [comment]
Closed after merging the PR
